#!/bin/bash

function split_card() {
  dir="$1"
  [[ -f "$dir"/Card\ 1 ]] \
    && gcsplit --prefix="$dir"/front --suffix-format='%0d.html' "$dir"/Card\ 1 '/[\S\s]*```/' {*}
  mv "$dir"/front0.html "$dir"/front.html
  mv "$dir"/front1.html "$dir"/back.html
  sed -r '1s/^.{3}//' "$dir"/back.html >"$dir"/back2.html && mv "$dir"/back2.html "$dir"/back.html
}

function main() {
  [ ! "$(ls templates)" ] && printf "templates folder either doesn't exist or is empty. exiting..." \
    && exit 1
  local has_unsupported_card_type
  for dir in templates/*; do
    local note_type
    note_type=$(basename -- "$dir")
    note_type="${note_type%.*}"
    for file in "$dir"/*; do
      [[ -f "$dir/front.html" || -f "$dir/back.html" ]] && echo "HTML files were found. Maybe you meant to run combine" \
        && exit 1
      [[ $file != "$dir/style.css" && $file != "$dir/Card 1" ]] \
        && echo "Only a single card type ('Card 1') is supported. Please try again after removing the note type: '$note_type' " \
        && has_unsupported_card_type="true"
    done
  done
  [[ $has_unsupported_card_type == "true" ]] \
    && exit 1

  for dir in templates/*; do
    for file in "$dir"/*; do
      local split_card
      split_card=$(split_card "$dir")
      rm "$dir"/Card\ ?
    done
  done
}

main "$@"
